on:
  create

jobs:
  branch-created:
    # This job only runs for issue comments
    name: Branch created
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        id: variables
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.ref.split("/").pop())
