on:
  create

jobs:
  branch-created:
    # This job only runs for issue comments
    name: Branch created
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Variables
        id: variables
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.ref.split("/").pop().slice(1),
              owner: 'rusaliya',
              repo: 'github-automation',
              labels: ["In Progress"]
            })
