on:
  create

jobs:
  branch-created:
    # This job only runs for issue comments
    name: Branch created
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - run:
          echo github.event.ref
