name: Add 'Done' labeled issues to 'Done' column

on:
  issues:
    types: labeled
jobs:
  add-to-done:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.TEST_TOKEN  }}"
        project-url: "https://github.com/users/rusaliya/projects/9"
        column-name: "Done"
        label-name: "Done"
